Repository woorifisa-projects-3rd/Crews-FE, pull requests merged in 2024-12, with the labels that each got.

#73 아지트 모임통장부분 api 연결
  apis/agitsAPI.js
  app/service/agits/[agitId]/accounts/dues/manage/page.jsx
  app/service/agits/[agitId]/accounts/dues/page.jsx
  app/service/agits/[agitId]/accounts/page.jsx
  app/service/agits/[agitId]/page.jsx
  app/service/page.jsx
  components/agits/Account/Account.jsx
  components/agits/Account/AccountAndButton.jsx
  components/agits/Account/AccountAndHeader.jsx
  components/agits/Account/NoAccount.jsx
  components/agits/Account/NoAccount.module.css
  components/agits/Account/dues/ArrowButton.jsx
  components/agits/Account/dues/DateOfDues.jsx
  components/agits/Account/dues/FeePayment.jsx
  components/agits/Account/dues/FeePayment.module.css
  components/agits/Account/dues/TransferHistory.jsx
  components/agits/Account/dues/TransferHistory.module.css
  components/agits/Account/manage/DuesModal.jsx
  components/agits/Account/manage/DuesModalContent.jsx
  components/agits/Account/manage/DuesModalContent.module.css
  components/agits/Account/manage/ProfileCard.jsx
  components/agits/Account/manage/ProfileCard.module.css
Labels: Feature

#79 [refact/#78]: 주소 API 코드 분리
  app/service/(auth)/signup/(step)/step2/page.jsx
  app/service/mypage/(update)/address/page.jsx
  components/auth/signup/ActivityArea.jsx
  components/common/AddressPostcode/AddressFormField.jsx
  components/common/AddressPostcode/AddressPostcode.jsx
  components/common/AddressPostcode/AddressSearchModal.jsx
  components/common/AddressPostcode/index.js
  components/common/index.js
  components/mypage/form/AddressForm.jsx
  constants/address.js
  utils/address.js
Labels: Feature

#83 75 search page connect api
  apis/agitsAPI.js
  apis/searchAPI.js
  app/service/search/page.jsx
  components/agits/ApplyModalContent.jsx
  components/common/ImageCard/ImageCard.jsx
  components/search/SearchForm.jsx
  components/search/SearchResult.jsx
Labels: Feature

#85 [Feat#84]: Agit_Create_Connect_To_API
  apis/agitsAPI.js
  app/service/agits/create/done/page.jsx
  app/service/agits/create/page.jsx
  components/agits/create/AgitCreateForm.jsx
Labels: Feature

#88 80 front back connect api
  apis/agitsAPI.js
  app/service/agits/[agitId]/accounts/create/page.jsx
  app/service/agits/[agitId]/accounts/dues/manage/page.jsx
  app/service/agits/[agitId]/accounts/dues/page.jsx
  app/service/agits/[agitId]/accounts/page.jsx
  app/service/agits/[agitId]/page.jsx
  components/agits/Account/AccountAndButton.jsx
  components/agits/Account/AccountAndHeader.jsx
  components/agits/Account/AccountCreate.jsx
  components/agits/Account/AccountDetail.jsx
  components/agits/Account/AccountHistory.jsx
  components/agits/Account/AccountHistoryFilter.jsx
  components/agits/Account/dues/ArrowButton.jsx
  components/agits/Account/dues/DateOfDues.jsx
  components/agits/Account/dues/FeePayment.jsx
  components/agits/Account/manage/DuesCheckbox.jsx
  components/agits/Account/manage/DuesCheckbox.module.css
  components/agits/Account/manage/DuesManage.jsx
  components/agits/Account/manage/DuesModal.jsx
  components/agits/Account/manage/DuesModalContent.jsx
  components/agits/Account/manage/ProfileCard.jsx
  components/agits/AgitHeader.jsx
  components/common/ImageCard/ImageCard.jsx
  components/common/PinNumber/PinNumber.jsx
  constants/dummy.js
  constants/selectMenuList/sample.js
  utils/date.js
Labels: Feature

#89 [feat/#82]: 메인 API 연결 및 모임통장 개설완료 모달 구현
  apis/agitsAPI.js
  app/error.jsx
  app/sample/layout.jsx
  app/sample/page.jsx
  app/sample/write/page.jsx
  app/service/agits/page.jsx
  app/service/page.jsx
  app/service/page.module.css
  components/ServiceMain.jsx
  components/ServiceMain.module.css
  components/agits/Account/AccountCreate.jsx
  components/agits/Account/AccountCreate.module.css
  components/agits/ApplyModalContent.jsx
  components/agits/ApplyModalContent.module.css
  components/agits/SubjectAgitList.jsx
  components/agits/create/AgitCreateForm.jsx
  components/common/ImageCard/ImageCard.jsx
  components/common/ImageCard/ImageCard.module.css
  components/common/Landing/Landing.jsx
  components/common/Skeleton/ImageCardSkeleton.jsx
  components/common/Skeleton/index.js
  components/common/index.js
  components/sample/PostForm.jsx
  components/sample/PostsList.jsx
  components/search/SearchResult.jsx
  constants/tabMenuList/service.js
  styles/common.css
Labels: Feature

#90 [fix]: ProfileCard 경로 대소문자 수정
  app/service/mypage/(profile)/layout.jsx
Labels: Bug

#94 [fix] 종합 업데이트
  app/service/agits/page.jsx
  components/ServiceMain.jsx
  components/mypage/MyAgitList.jsx
  components/search/SearchResult.jsx
  middleware.js
  styles/reset.css
Labels: Feature

#98 [feat/#81]: 관리자 구현
  apis/adminAPI.js
  app/admin/layout.jsx
  app/admin/page.jsx
  app/service/layout.jsx
  auth.js
  components/admin/ComplaintList.jsx
  components/admin/ComplaintList.module.css
  components/admin/ReportModalContent.jsx
  components/agits/ApplyModalContent.jsx
  components/common/Navigation/NavigationAdmin.jsx
  components/common/Navigation/NavigationAdmin.module.css
  components/common/Navigation/NavigationService.jsx
  components/common/Navigation/NavigationService.module.css
  components/common/Navigation/index.js
  components/common/Skeleton/TableRowSkeleton.jsx
  components/common/Skeleton/index.js
  components/common/index.js
  next.config.mjs
  styles/common.css
  styles/reset.css
Labels: Feature

#97 Cypress 테스트 코드 작성
  apis/agitsAPI.js
  app/service/agits/[agitId]/page.jsx
  components/agits/Account/Account.jsx
  components/agits/Account/AccountAndButton.jsx
  components/agits/Account/AccountAndHeader.jsx
  components/agits/Account/AccountCreate.jsx
  components/agits/Account/AccountHistoryFilter.jsx
  components/agits/Account/dues/FeePayment.jsx
  components/agits/Account/manage/DuesManage.jsx
  components/agits/Account/manage/DuesModal.jsx
  components/agits/Account/manage/DuesModalContent.jsx
  components/agits/Account/manage/ProfileCard.jsx
  components/common/Button/ButtonM.jsx
  components/common/ImageCard/ImageCard.jsx
  components/mypage/ProfileCard/ProfileCard.jsx
  constants/auth.js
  constants/selectMenuList/sample.js
  cypress.config.js
  cypress/e2e/accessUrlToAgit.cy.js
  cypress/e2e/duesCall.cy.js
  cypress/e2e/generateAccount.cy.js
  cypress/e2e/generateAgit.cy.js
  cypress/e2e/joinInAgit.cy.js
  cypress/e2e/login_logout.cy.js
  cypress/e2e/transferDues.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: Feature

#100 refactor/#99: 모임 회비 납부 버튼 비활성화 및 mutate처리
  components/common/PinNumber/PinNumber.jsx
  components/mypage/MembershipFee/MembershipFee.jsx
Labels: Fix

#102 [Fix#86]: Fix_Infinite_Getting_Result
  components/payment/PaymentMain.jsx
Labels: Fix

#104 [Fix#86]: RollBack_Infinity_Call_And_Time
  components/payment/PaymentMain.jsx
Labels: Fix

#105 api수정
  apis/agitsAPI.js
  app/service/agits/[agitId]/accounts/create/page.jsx
  components/agits/Account/dues/FeePayment.jsx
Labels: Feature

#107 [Fix#106]: Update_Local_Storage
  components/search/SearchResult.jsx
Labels: Fix

#108 [feat/#82]: 가입신청시 localStorage 갱신
  components/ServiceMain.jsx
Labels: Fix

#110 82 service main api
  components/agits/ProfileCardList.jsx
  components/common/PinNumber/PinNumber.jsx
  components/mypage/MyAgitList.jsx
Labels: Fix
